import { GitHubBanner } from "@refinedev/core";
import { Metadata } from "next";
import { cookies } from "next/headers";
import React, { Suspense } from "react";

import { RefineClientProviders } from "@components/refine-client-providers";
import AppLayout from "@components/AppLayout"; // 🌟 Yeni Ekledik
import "@refinedev/antd/dist/reset.css";

export const metadata: Metadata = {
  title: "Libristo Admin",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const theme = cookieStore.get("theme");
  const defaultMode = theme?.value === "dark" ? "dark" : "light";

  return (
    <html lang="en">
      <body>
        <Suspense>
          <RefineClientProviders defaultMode={defaultMode}>
            {/* 🌟 Bütün sayfaları Navbar bileşenimizle sarıyoruz */}
            <AppLayout>
              {children}
            </AppLayout>
          </RefineClientProviders>
        </Suspense>
      </body>
    </html>
  );
}